export const CARD_CONSTANTS = {
    LEARNING_STEPS: [1, 10],
    RELEARNING_STEPS: [1, 5],
    GRADUATING_INTERVAL: 1,
    EASY_INTERVAL: 4,
    INITIAL_EASE: 2.5,
    EASY_BONUS: 1.3,
    MIN_EASE: 1.3,
    MAX_INTERVAL: 36500,
    DEFAULT_LIMIT: 20,
    MAX_LIMIT: 200,
} as const;
