import { AppConfig } from './app.config';

export const JwtConfig = {
  ACCESS_TOKEN_SECRET: AppConfig.JWT_ACCESS_SECRET,
  ACCESS_TOKEN_EXPIRE: AppConfig.JWT_ACCESS_EXPIRE,
  REFRESH_TOKEN_SECRET: AppConfig.JWT_REFRESH_SECRET,
  REFRESH_TOKEN_EXPIRE: AppConfig.JWT_REFRESH_EXPIRE,
};
